export const categoryOptions = [
  'All',
  'Cups & Lids',
  'Food Containers',
  'Paper Packaging',
  'Pizza',
  'Accessories',
  'Custom',
] as const

export type ProductCategory = Exclude<(typeof categoryOptions)[number], 'All'>

export type Product = {
  id: string
  sku?: string
  name: string
  category: ProductCategory
  material: string
  description: string
  casePack: string
  leadTime: string
  image: string
  badges: string[]
  applications: string[]
  sizes: string[]
  unitPrice?: number | null
  unitsPerCase?: number
  stockType?: string
  source?: 'crm' | 'curated'
}

const images = {
  paperCup:
    'https://static.wixstatic.com/media/067fd2_cd63d937ea0b4f5d970719418042c4a7~mv2.jpeg/v1/crop/x_1830,y_0,w_5340,h_6000/fill/w_890,h_1000,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/papercupwithpapersleeve.jpeg',
  clearCup:
    'https://static.wixstatic.com/media/067fd2_dcba4a3a1e104ac3b9fb7399dc7eb054~mv2.jpg/v1/fill/w_890,h_514,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/plasticcupbeerserving.jpg',
  tray:
    'https://static.wixstatic.com/media/067fd2_59fab9c03a7c41599a037342b9aebc94~mv2.jpeg/v1/crop/x_118,y_565,w_4769,h_2540/fill/w_1858,h_990,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/plastic%20cup%20with%20fruit.jpeg',
  paperPackaging:
    'https://static.wixstatic.com/media/067fd2_81c9663dd29449a29611123b88c3816b~mv2.jpeg/v1/fill/w_896,h_610,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/papercupscheers.jpeg',
  custom:
    'https://static.wixstatic.com/media/067fd2_95949ec8a878425ca9c1c55b49f201dc~mv2.jpeg/v1/crop/x_0,y_17,w_4000,h_4125/fill/w_894,h_922,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/plasticcup.jpeg',
}

const confirmCasePack = 'Confirmed with order'
const confirmLeadTime = 'Confirmed with order'

export const products: Product[] = [
  {
    id: 'paper-cups',
    name: 'Paper beverage cups',
    category: 'Cups & Lids',
    material: 'Coated paper cupstock; material route confirmed by program',
    description: 'Hot and cold beverage cup programs with coordinated lids, sleeves, and custom-print options.',
    casePack: confirmCasePack,
    leadTime: confirmLeadTime,
    image: images.paperCup,
    badges: ['6–32 oz range', 'Custom print', 'Hot + cold'],
    applications: ['Coffee', 'QSR', 'Convenience', 'Foodservice'],
    sizes: ['6–12 oz range', '16–20 oz range', '24–32 oz range', 'Custom capacity'],
  },
  {
    id: 'clear-cups',
    name: 'Clear beverage cups',
    category: 'Cups & Lids',
    material: 'PET-family, recycled-content, and other routes by program',
    description: 'High-clarity cold-cup programs for beverages, stadiums, convenience stores, and prepared-drink service.',
    casePack: confirmCasePack,
    leadTime: confirmLeadTime,
    image: images.clearCup,
    badges: ['Multiple rim formats', 'Print options', 'Cold beverage'],
    applications: ['Beverage', 'Events', 'Convenience', 'Foodservice'],
    sizes: ['Small beverage format', 'Medium beverage format', 'Large beverage format', 'Custom capacity'],
  },
  {
    id: 'portion-cups',
    name: 'Portion cups and lids',
    category: 'Cups & Lids',
    material: 'Plastic material selected for product and use case',
    description: 'Portion packaging for sauces, condiments, samples, sides, and grab-and-go programs.',
    casePack: confirmCasePack,
    leadTime: confirmLeadTime,
    image: images.clearCup,
    badges: ['1–32 oz range', 'Lid programs', 'Foodservice'],
    applications: ['QSR', 'Prepared foods', 'Convenience', 'Food processors'],
    sizes: ['1–4 oz range', '5–12 oz range', '16–32 oz range', 'Custom capacity'],
  },
  {
    id: 'paper-food-cups',
    name: 'Paper food cups and bowls',
    category: 'Cups & Lids',
    material: 'Coated paperboard selected for the intended use',
    description: 'Coordinated food cups and bowls for sides, soups, desserts, hot foods, and prepared-food programs.',
    casePack: confirmCasePack,
    leadTime: confirmLeadTime,
    image: images.paperCup,
    badges: ['Multiple capacities', 'Lid matching', 'Custom print'],
    applications: ['Prepared foods', 'Takeout', 'Deli & bakery', 'QSR'],
    sizes: ['Small food-cup format', 'Medium food-cup format', 'Large bowl format', 'Custom capacity'],
  },
  {
    id: 'cup-lids-sleeves',
    name: 'Cup lids and sleeves',
    category: 'Cups & Lids',
    material: 'Paper and plastic accessories matched to the cup program',
    description: 'Lids, sleeves, and coordinated accessories selected around rim compatibility and service conditions.',
    casePack: confirmCasePack,
    leadTime: confirmLeadTime,
    image: images.paperCup,
    badges: ['Compatibility review', 'Hot + cold', 'Program matched'],
    applications: ['Coffee', 'Beverage', 'QSR', 'Convenience'],
    sizes: ['Match an existing NexGen cup', 'Match a customer cup', 'New cup-and-lid program'],
  },
  {
    id: 'beverage-bottles',
    name: 'Beverage bottles',
    category: 'Cups & Lids',
    material: 'Clear plastic bottle material selected by program',
    description: 'Bottle formats for prepared beverages, juice, refrigerated grab-and-go, and private-label programs.',
    casePack: confirmCasePack,
    leadTime: confirmLeadTime,
    image: images.clearCup,
    badges: ['Clear format', 'Closure matching', 'Private label'],
    applications: ['Beverage', 'Retail', 'Convenience', 'Food processors'],
    sizes: ['Standard bottle format', 'Large bottle format', 'Custom bottle program'],
  },
  {
    id: 'produce-trays',
    name: 'Produce and protein trays',
    category: 'Food Containers',
    material: 'PET-family and program-specific plastic options',
    description: 'High-clarity tray programs for produce, proteins, merchandising, and refrigerated prepared foods.',
    casePack: confirmCasePack,
    leadTime: confirmLeadTime,
    image: images.tray,
    badges: ['High clarity', 'Anti-fog options', 'Retail display'],
    applications: ['Produce', 'Retail', 'Deli & bakery', 'Food processors'],
    sizes: ['Small tray format', 'Medium tray format', 'Family-pack tray', 'Custom footprint'],
  },
  {
    id: 'hinged-clamshells',
    name: 'Hinged clamshell containers',
    category: 'Food Containers',
    material: 'Rigid plastic selected for clarity and service conditions',
    description: 'One-piece hinged containers for takeout, bakery, prepared meals, produce, and grab-and-go merchandising.',
    casePack: confirmCasePack,
    leadTime: confirmLeadTime,
    image: images.tray,
    badges: ['One-piece format', 'Clear options', 'Grab-and-go'],
    applications: ['Takeout', 'Deli & bakery', 'Convenience', 'Prepared foods'],
    sizes: ['Small hinged format', 'Medium hinged format', 'Large hinged format', 'Custom footprint'],
  },
  {
    id: 'two-piece-containers',
    name: 'Two-piece containers and lids',
    category: 'Food Containers',
    material: 'Rigid plastic base and lid routes by program',
    description: 'Separate base-and-lid systems for ready meals, deli, produce, sides, and display-focused food programs.',
    casePack: confirmCasePack,
    leadTime: confirmLeadTime,
    image: images.tray,
    badges: ['Base + lid', 'Anti-fog options', 'Retail ready'],
    applications: ['Prepared foods', 'Retail', 'Deli & bakery', 'Food processors'],
    sizes: ['Small two-piece format', 'Medium two-piece format', 'Large two-piece format', 'Custom footprint'],
  },
  {
    id: 'deli-dessert-cups',
    name: 'Deli and dessert cups',
    category: 'Food Containers',
    material: 'Clear plastic material selected by product requirements',
    description: 'Round and specialty cup programs for deli sides, parfaits, desserts, chilled foods, and merchandising.',
    casePack: confirmCasePack,
    leadTime: confirmLeadTime,
    image: images.custom,
    badges: ['High clarity', 'Lid matching', 'Cold case'],
    applications: ['Deli & bakery', 'Dessert', 'Retail', 'Convenience'],
    sizes: ['Small cup format', 'Medium cup format', 'Large cup format', 'Custom capacity'],
  },
  {
    id: 'ready-meal-containers',
    name: 'Ready-meal containers',
    category: 'Food Containers',
    material: 'Material selected for filling, handling, display, and reheating needs',
    description: 'Prepared-meal packaging considered alongside filling lines, sealing, handling, distribution, and presentation.',
    casePack: confirmCasePack,
    leadTime: confirmLeadTime,
    image: images.tray,
    badges: ['Processor focused', 'Operational fit', 'Custom development'],
    applications: ['Prepared foods', 'Food processors', 'Retail', 'Convenience'],
    sizes: ['Single-compartment format', 'Multi-compartment format', 'Family-meal format', 'Custom footprint'],
  },
  {
    id: 'family-entree-containers',
    name: 'Family-pack and entrée containers',
    category: 'Food Containers',
    material: 'Rigid plastic material selected by program',
    description: 'Larger-format food containers for entrées, family meals, catering, and high-volume takeout programs.',
    casePack: confirmCasePack,
    leadTime: confirmLeadTime,
    image: images.tray,
    badges: ['Large format', 'Takeout', 'Program based'],
    applications: ['Takeout', 'Prepared foods', 'Catering', 'QSR'],
    sizes: ['Entrée format', 'Family-pack format', 'Catering format', 'Custom footprint'],
  },
  {
    id: 'paper-takeout-boxes',
    name: 'Paper takeout and chicken boxes',
    category: 'Paper Packaging',
    material: 'Paperboard or fluted board selected for the food and distribution route',
    description: 'Folded and formed paper packaging for takeout meals, chicken, shared portions, and branded foodservice programs.',
    casePack: confirmCasePack,
    leadTime: confirmLeadTime,
    image: images.paperPackaging,
    badges: ['Formed carton', 'Custom print', 'Takeout'],
    applications: ['QSR', 'Takeout', 'Delivery', 'Convenience'],
    sizes: ['Single-serving format', 'Shareable format', 'Large takeout format', 'Custom structure'],
  },
  {
    id: 'paper-food-trays',
    name: 'Paper food trays and boats',
    category: 'Paper Packaging',
    material: 'Paperboard or fluted material selected by program',
    description: 'Open-top paper trays for concessions, prepared foods, sides, sampling, and fast-casual service.',
    casePack: confirmCasePack,
    leadTime: confirmLeadTime,
    image: images.paperPackaging,
    badges: ['Open-top format', 'Custom print', 'Foodservice'],
    applications: ['Events', 'QSR', 'Prepared foods', 'Convenience'],
    sizes: ['Small tray format', 'Medium tray format', 'Large tray format', 'Custom structure'],
  },
  {
    id: 'specialty-food-cartons',
    name: 'Fry, burger, sandwich, and sub cartons',
    category: 'Paper Packaging',
    material: 'Paperboard selected for structure, print, and food-contact needs',
    description: 'Purpose-built paper cartons for common QSR menu items and coordinated branded packaging programs.',
    casePack: confirmCasePack,
    leadTime: confirmLeadTime,
    image: images.paperPackaging,
    badges: ['Menu specific', 'Custom print', 'Formed carton'],
    applications: ['QSR', 'Takeout', 'Delivery', 'Convenience'],
    sizes: ['Fry carton', 'Burger carton', 'Sandwich or hot-dog carton', 'Sub carton', 'Custom structure'],
  },
  {
    id: 'food-buckets',
    name: 'Paper food buckets',
    category: 'Paper Packaging',
    material: 'Coated paperboard selected for the intended food program',
    description: 'Large-capacity buckets for chicken, snacks, shared meals, entertainment venues, and branded promotions.',
    casePack: confirmCasePack,
    leadTime: confirmLeadTime,
    image: images.paperCup,
    badges: ['32–128 oz range', 'Custom print', 'Shareable'],
    applications: ['QSR', 'Events', 'Takeout', 'Delivery'],
    sizes: ['32–64 oz range', '85–128 oz range', 'Custom capacity'],
  },
  {
    id: 'beverage-carriers',
    name: 'Beverage carriers',
    category: 'Paper Packaging',
    material: 'Paperboard or molded-fiber route selected by program',
    description: 'Carry solutions coordinated with cup sizes, order patterns, branding, and takeout operations.',
    casePack: confirmCasePack,
    leadTime: confirmLeadTime,
    image: images.paperPackaging,
    badges: ['Cup matched', 'Takeout', 'Program coordinated'],
    applications: ['Coffee', 'Beverage', 'QSR', 'Delivery'],
    sizes: ['Standard carrier format', 'Large-order carrier format', 'Custom carrier program'],
  },
  {
    id: 'smartbox-smartview',
    name: 'SmartBox and SmartView packages',
    category: 'Paper Packaging',
    material: 'Paperboard and windowed structures by program',
    description: 'Specialty formed-paper packages developed around food visibility, branding, handling, and presentation.',
    casePack: confirmCasePack,
    leadTime: confirmLeadTime,
    image: images.paperPackaging,
    badges: ['Specialty structure', 'Custom development', 'Display focused'],
    applications: ['Deli & bakery', 'Retail', 'Prepared foods', 'Takeout'],
    sizes: ['Standard package format', 'Windowed package format', 'Custom structure'],
  },
  {
    id: 'ultraone',
    name: 'UltraOne container and lid',
    category: 'Pizza',
    material: 'Material and construction confirmed with the ULTRA program',
    description: 'A premium container-and-lid system designed for takeout and delivery performance.',
    casePack: confirmCasePack,
    leadTime: confirmLeadTime,
    image: images.custom,
    badges: ['ULTRA collection', 'Container + lid', 'Delivery'],
    applications: ['Pizza', 'Takeout', 'Delivery', 'Convenience'],
    sizes: ['Standard UltraOne format', 'Custom program'],
  },
  {
    id: 'ultracrust',
    name: 'UltraCrust pizza insert',
    category: 'Pizza',
    material: 'Construction and performance specifications require NexGen confirmation',
    description: 'A pizza-program insert from the ULTRA collection for takeout and delivery applications.',
    casePack: confirmCasePack,
    leadTime: confirmLeadTime,
    image: images.paperPackaging,
    badges: ['ULTRA collection', 'Pizza delivery', 'Sample available'],
    applications: ['Pizza', 'Takeout', 'Delivery', 'QSR'],
    sizes: ['12 × 12 in sample format', 'Custom program'],
  },
  {
    id: 'pizza-boxes',
    name: 'Full-size pizza boxes',
    category: 'Pizza',
    material: 'Recycled-fiber, paperboard, and fluted routes by program',
    description: 'Branded pizza boxes developed around size, structure, delivery conditions, print, and operating volume.',
    casePack: confirmCasePack,
    leadTime: confirmLeadTime,
    image: images.paperPackaging,
    badges: ['Custom print', 'Multiple structures', 'Delivery'],
    applications: ['Pizza', 'QSR', 'Takeout', 'Delivery'],
    sizes: ['7 × 7 in sample format', '12 × 12 in sample format', 'Custom pizza size'],
  },
  {
    id: 'slice-boxes',
    name: 'Slice and personal pizza boxes',
    category: 'Pizza',
    material: 'Paperboard or fluted construction by program',
    description: 'Compact pizza packaging for slices, personal pizzas, grab-and-go service, and convenience foodservice.',
    casePack: confirmCasePack,
    leadTime: confirmLeadTime,
    image: images.paperPackaging,
    badges: ['ULTRA collection', 'Grab-and-go', 'Custom print'],
    applications: ['Pizza', 'Convenience', 'QSR', 'Takeout'],
    sizes: ['8.5 × 9 in slice-box sample', '7 × 7 in personal-box sample', 'Custom size'],
  },
  {
    id: 'pizza-liners',
    name: 'Pizza-box liners and inserts',
    category: 'Pizza',
    material: 'Paper-based construction confirmed by product program',
    description: 'Insert and liner options coordinated with the pizza box, product, delivery time, and service model.',
    casePack: confirmCasePack,
    leadTime: confirmLeadTime,
    image: images.paperPackaging,
    badges: ['Box matched', 'Delivery focused', 'Program based'],
    applications: ['Pizza', 'Takeout', 'Delivery', 'QSR'],
    sizes: ['12 × 12 in sample format', 'Match an existing box', 'Custom liner size'],
  },
  {
    id: 'takeout-bags',
    name: 'Takeout bags',
    category: 'Accessories',
    material: 'Paper and program-specific material routes',
    description: 'Carryout bags coordinated with packaging formats, order sizes, branding, and delivery operations.',
    casePack: confirmCasePack,
    leadTime: confirmLeadTime,
    image: images.paperPackaging,
    badges: ['Paper options', 'Custom print', 'Program coordinated'],
    applications: ['Takeout', 'Delivery', 'QSR', 'Retail'],
    sizes: ['Small order format', 'Medium order format', 'Large order format', 'Custom bag size'],
  },
  {
    id: 'foodservice-accessories',
    name: 'Foodservice accessories',
    category: 'Accessories',
    material: 'Material varies by accessory and sourcing route',
    description: 'Straws, cutlery, napkins, liners, and related accessories assembled into a coordinated packaging program.',
    casePack: confirmCasePack,
    leadTime: confirmLeadTime,
    image: images.paperCup,
    badges: ['Mixed bill of goods', 'Sourced options', 'Program coordinated'],
    applications: ['Foodservice', 'QSR', 'Convenience', 'Events'],
    sizes: ['Straws', 'Cutlery', 'Napkins', 'Food liners', 'Coordinated accessory set'],
  },
  {
    id: 'custom-program',
    name: 'Custom printed packaging program',
    category: 'Custom',
    material: 'Paper, plastic, or coordinated mixed bill of goods',
    description: 'Artwork, prototyping, tooling, forecasting, warehousing, and replenishment coordinated around the customer program.',
    casePack: 'MOQ confirmed by item',
    leadTime: 'Project schedule',
    image: images.custom,
    badges: ['Paper + plastic', 'Custom print', 'Program management'],
    applications: ['Multi-unit', 'Private label', 'Franchise', 'Food processors'],
    sizes: ['Single custom product', 'Coordinated product set', 'Mixed bill of goods'],
  },
  {
    id: 'private-label-program',
    name: 'Private-label packaging program',
    category: 'Custom',
    material: 'Product-specific paper, plastic, and sourced materials',
    description: 'A managed path for branded product development, supplier coordination, inventory planning, and fulfillment.',
    casePack: 'MOQ confirmed by item',
    leadTime: 'Project schedule',
    image: images.custom,
    badges: ['Private label', 'Inventory planning', 'Fulfillment'],
    applications: ['Private label', 'Retail', 'Multi-unit', 'Food processors'],
    sizes: ['Single private-label item', 'Product family', 'Multi-SKU program'],
  },
]

export const applicationOptions = [
  'All applications',
  ...Array.from(new Set(products.flatMap((product) => product.applications))),
]

export const quoteQuantityOptions = [1, 5, 10, 25, 50, 100, 250]
