import {useState} from 'react'
import {Link,useNavigate,useLocation} from 'react-router-dom'
import type {CustomerQuoteHistoryEntry} from './customerAccount'
import {formatPortalDate,quoteLink} from './portalPresentation'
import {PortalError,PortalSkeleton} from './PortalFeedback'
export function PortalQuoteList({requests,status,error,refresh}:{requests:CustomerQuoteHistoryEntry[];status:'loading'|'ready'|'error';error:string;refresh:()=>void}){
 const navigate=useNavigate(),location=useLocation()
 const [query,setQuery]=useState(new URLSearchParams(location.search).get('search')||''),[filter,setFilter]=useState(new URLSearchParams(location.search).get('status')||'All'),[sort,setSort]=useState('newest'),[page,setPage]=useState(0)
 const statuses=['All','Submitted','In review','Quote ready','Accepted','Changes requested','Expired','Quote withdrawn','Declined']
 const matched=requests.filter(request=>(filter==='All'||filter===request.status)&&[request.requestNumber,request.issuedQuoteNumber,request.purchaseOrder,...request.items.map(item=>item.productName+' '+item.sku)].join(' ').toLowerCase().includes(query.trim().toLowerCase()))
 const ordered=[...matched].sort((a,b)=>sort==='number'?a.requestNumber.localeCompare(b.requestNumber):sort==='oldest'?a.submittedAt.localeCompare(b.submittedAt):b.submittedAt.localeCompare(a.submittedAt))
 const last=Math.max(0,Math.ceil(ordered.length/20)-1),current=Math.min(page,last),rows=ordered.slice(current*20,current*20+20)
 return <section className="account-content-card portal-list-view" aria-label="Quote request history"><div className="portal-list-controls"><label>Search quotes<input type="search" value={query} onChange={e=>{setQuery(e.target.value);setPage(0)}} placeholder="Request, quote, PO or product" /></label><label>Sort<select value={sort} onChange={e=>{setSort(e.target.value);setPage(0)}}><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="number">Request number</option></select></label><button type="button" disabled={status==='loading'} onClick={refresh}>Refresh</button></div>
 <div className="portal-status-filters" aria-label="Filter by quote status">{statuses.map(value=><button type="button" key={value} aria-pressed={value===filter} onClick={()=>{setFilter(value);setPage(0)}}>{value}</button>)}</div>
 {status==='loading'&&!requests.length?<PortalSkeleton label="Loading your quotes…"/>:<>{status==='error'&&<PortalError message={error||'Quotes could not load.'} onRetry={refresh}/>}
 {!requests.length&&status!=='error'?<div className="account-empty-state"><strong>No quote requests yet.</strong><p>Start with Request a quote.</p><Link to="/products">Request a quote</Link></div>:!rows.length?<p>No requests match your search and filters.</p>:<><div className="portal-quote-table"><table><thead><tr><th>Request / quote</th><th>Submitted</th><th>Status</th><th>Items</th><th>Total</th><th>Valid through</th></tr></thead><tbody>{rows.map(request=><tr key={request.requestNumber} onClick={e=>{if(!(e.target instanceof Element)||!e.target.closest('a,button'))navigate(quoteLink(request.requestNumber))}}><td><Link to={quoteLink(request.requestNumber)}>{request.requestNumber}</Link>{request.issuedQuoteNumber&&<small>{request.issuedQuoteNumber}</small>}{request.purchaseOrder&&<small>PO: {request.purchaseOrder}</small>}</td><td>{formatPortalDate(request.submittedAt)}</td><td><span className="account-quote-status">{request.status}</span></td><td>{request.items.slice(0,2).map((item,i)=><small key={i}>{item.productName} · {item.cases} {item.cases===1?'case':'cases'}</small>)}{request.items.length>2&&<small>+{request.items.length-2} more</small>}</td><td>{request.quoteTotal===null||request.quoteTotal===undefined?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:request.currency||'USD'}).format(request.quoteTotal)}</td><td>{request.validThrough?formatPortalDate(request.validThrough):'—'}</td></tr>)}</tbody></table></div><nav className="portal-pagination" aria-label="Quote pages"><button type="button" disabled={current===0} onClick={()=>setPage(current-1)}>Previous</button><span>Page {current+1} of {last+1} · {matched.length} requests</span><button type="button" disabled={current===last} onClick={()=>setPage(current+1)}>Next</button></nav></>}
 </>}
 </section>
}
